name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  CONFIGURATION: Release
  CORS: 'Jokk.Microservice.Cors'
  POLLY: 'Jokk.Microservice.Polly'
  SWAGGER: 'Jokk.Microservice.Swagger'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c $CONFIGURATION --no-restore
      
  nuget:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Authenticate to Github nuget registry
      run: dotnet nuget add source --username jokk-itu --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/jokk-itu/index.json"
      shell: bash
      
    - name: Push packages
      run: |
        cors_package=$(ls *nupkg)
        dotnet nuget push "$CORS/bin/$CONFIGURATION/$cors_package" --source "github" --skip-duplicate
      shell: bash
