name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  CONFIGURATION: Release

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix: 
        projects: ['Jokk.Microservice.Cors', 'Jokk.Microservice.Polly', 'Jokk.Microservice.Swagger', 'Jokk.Microservice.Log', 'Jokk.Microservice.Prometheus']

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ${{ matrix.projects }}/${{ matrix.projects }}.csproj -c $CONFIGURATION --no-restore
    - name: authenticate github nuget registry
      run: dotnet nuget add source --username jokk-itu --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/jokk-itu/index.json"
    - name: push packages to github nuget registry
      run: |
        package=$(ls ${{ matrix.projects }}/bin/$CONFIGURATION/*nupkg)
        dotnet nuget push "$package" --source "github" --skip-duplicate
